/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.pb.aquajama;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.pb.aquajama.agent.tools.AgentTool;
import com.pb.aquajama.agent.tools.ToolRegistry;
import com.pb.aquajama.data.Config;
import com.pb.aquajama.ollama.Client;
import com.pb.aquajama.ollama.Model;
import com.pb.aquajama.sessions.Session;
import java.beans.PropertyVetoException;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.util.List;
import javax.swing.JMenuItem;

/**
 *
 * @author patrickballeux
 */
public class aquaJamaDesktop extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(aquaJamaDesktop.class.getName());
    private final Config config;
    private final Client client;
    private List<Model> models;
    private List<AgentTool> tools;

    /**
     * Creates new form aquaJamaDesktop
     */
    public aquaJamaDesktop() {
        initComponents();
        this.config = new Config();
        this.client = new Client(Client.LOCAL_URL);  // start with local
        this.tools = ToolRegistry.createDefaultTools(new ObjectMapper());
        initNewSessionMenu();
        var icon = new javax.swing.ImageIcon(getClass().getResource("/icons/logo.png")).getImage();
        this.setIconImage(icon);
        try {
            Class<?> taskbarClass = Class.forName("java.awt.Taskbar");
            Method getTaskbar = taskbarClass.getMethod("getTaskbar");
            Object taskbar = getTaskbar.invoke(null);
            Method setIconImage = taskbar.getClass().getMethod("setIconImage", java.awt.Image.class);
            setIconImage.invoke(taskbar, icon);
        } catch (ClassNotFoundException | IllegalAccessException | NoSuchMethodException | InvocationTargetException e) {
            // Fallback: ignore on non-macOS or older Java
        }

    }

    private void initNewSessionMenu() {
        this.models = client.getModels();
        for (var m : models) {
            var menu = new JMenuItem(m.toString());
            menu.addActionListener(this::mnuModel_ActionPerformed);
            menu.setActionCommand(m.name());

            mnuNewSession.add(menu);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        panBottom = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        mnuSessions = new javax.swing.JMenu();
        mnuNewSession = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AquaJama Desktop");
        setSize(new java.awt.Dimension(694, 429));

        desktop.setName(""); // NOI18N

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 694, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );

        getContentPane().add(desktop, java.awt.BorderLayout.CENTER);

        jLabel1.setText("ALPHA");

        javax.swing.GroupLayout panBottomLayout = new javax.swing.GroupLayout(panBottom);
        panBottom.setLayout(panBottomLayout);
        panBottomLayout.setHorizontalGroup(
            panBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 694, Short.MAX_VALUE)
            .addGroup(panBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panBottomLayout.createSequentialGroup()
                    .addGap(0, 327, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 327, Short.MAX_VALUE)))
        );
        panBottomLayout.setVerticalGroup(
            panBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 17, Short.MAX_VALUE)
            .addGroup(panBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panBottomLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(panBottom, java.awt.BorderLayout.SOUTH);

        mnuSessions.setText("Sessions");

        mnuNewSession.setLabel("New");
        mnuSessions.add(mnuNewSession);

        menu.add(mnuSessions);

        setJMenuBar(menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuModel_ActionPerformed(java.awt.event.ActionEvent evt) {
        var modelName = evt.getActionCommand();
        var model = models.stream().filter(x -> (x.name() == null ? modelName == null : x.name().equals(modelName))).findFirst();
        Session session = new Session(model.get(), client,tools);
        var frame = new desktopSession(session);
        frame.setSize(300, 300);
        desktop.add(frame);
        frame.setVisible(true);
        try {
            frame.setSelected(true);
        } catch (PropertyVetoException ex) {
            System.getLogger(aquaJamaDesktop.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        System.setProperty("apple.laf.useScreenMenuBar", "true");
        System.setProperty("com.apple.mrj.application.apple.menu.about.name", "AquaJama Desktop");
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new aquaJamaDesktop().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenu mnuNewSession;
    private javax.swing.JMenu mnuSessions;
    private javax.swing.JPanel panBottom;
    // End of variables declaration//GEN-END:variables
}
