/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.pb.aquajama;

import com.pb.aquajama.ollama.Token;
import com.pb.aquajama.sessions.Session;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.KeyStroke;
import javax.swing.text.DefaultEditorKit;

/**
 *
 * @author patrickballeux
 */
public class desktopSession extends javax.swing.JInternalFrame {

    private final Session session;

    /**
     * Creates new form desktopSession
     *
     * @param session
     */
    public desktopSession(Session session) {
        initComponents();
        InputMap im = txtPrompt.getInputMap();
        ActionMap am = txtPrompt.getActionMap();

// ENTER → send message
        im.put(KeyStroke.getKeyStroke("ENTER"), "sendPrompt");

// SHIFT+ENTER → newline
        im.put(KeyStroke.getKeyStroke("shift ENTER"), "insertBreak");

        am.put("sendPrompt", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btnSend.doClick();
            }
        });

        am.put("insertBreak", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                txtPrompt.append("\n");
            }
        });
        this.session = session;
        this.setTitle("MODEL: %s".formatted(session.getModel().name()));
        session.setUiConsumer(token -> {
            javax.swing.SwingUtilities.invokeLater(() -> {
                // Basic append
                appendToken(token);
            });
        });
        txtResponse.setEditable(false);
        txtResponse.setWrapStyleWord(true);
        txtResponse.setLineWrap(true);

        lblModelName.setText(session.getModel().name());
        chkVision.setSelected(session.getModel().canUseVision());
        chkThink.setSelected(session.getModel().canThink());
        chkVision.setEnabled(false);
        chkThink.setEnabled(false);
        // Cross-platform copy binding
        int mask = Toolkit.getDefaultToolkit().getMenuShortcutKeyMaskEx();
        KeyStroke copyStroke = KeyStroke.getKeyStroke(KeyEvent.VK_C, mask);

        txtResponse.getInputMap().put(copyStroke, DefaultEditorKit.copyAction);
        txtResponse.getActionMap().get(DefaultEditorKit.copyAction);
        javax.swing.SwingUtilities.invokeLater(() -> txtPrompt.requestFocusInWindow());
        javax.swing.SwingUtilities.invokeLater(() -> this.pack());
    }

    private void appendToken(Token token) {

        if (token.isThinking()) {
            txtThinking.setText(txtThinking.getText().concat(token.text()));
            if (token.text().contains("\n")) {
                txtThinking.setText("");
            }
            return;
        }
        txtThinking.setText("");
        txtResponse.append(token.text());
        txtResponse.setCaretPosition(txtResponse.getDocument().getLength());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scroller = new javax.swing.JScrollPane();
        txtResponse = new javax.swing.JTextArea();
        panBottom = new javax.swing.JPanel();
        btnSend = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPrompt = new javax.swing.JTextArea();
        lblThinking = new javax.swing.JLabel();
        txtThinking = new javax.swing.JTextField();
        panTop = new javax.swing.JPanel();
        lblModel = new javax.swing.JLabel();
        lblModelName = new javax.swing.JLabel();
        chkVision = new javax.swing.JCheckBox();
        chkThink = new javax.swing.JCheckBox();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Session");
        setSize(new java.awt.Dimension(456, 227));
        setVisible(true);

        txtResponse.setColumns(20);
        txtResponse.setRows(5);
        scroller.setViewportView(txtResponse);

        getContentPane().add(scroller, java.awt.BorderLayout.CENTER);

        btnSend.setLabel("Send");
        btnSend.addActionListener(this::btnSendActionPerformed);

        txtPrompt.setColumns(20);
        txtPrompt.setLineWrap(true);
        txtPrompt.setRows(5);
        txtPrompt.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtPrompt);

        lblThinking.setText("Thinking");

        txtThinking.setEditable(false);
        txtThinking.setForeground(new java.awt.Color(153, 153, 153));
        txtThinking.setText(" ");

        javax.swing.GroupLayout panBottomLayout = new javax.swing.GroupLayout(panBottom);
        panBottom.setLayout(panBottomLayout);
        panBottomLayout.setHorizontalGroup(
            panBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBottomLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblThinking, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtThinking, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSend)
                .addContainerGap())
            .addGroup(panBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panBottomLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panBottomLayout.setVerticalGroup(
            panBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panBottomLayout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(panBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSend)
                    .addComponent(lblThinking)
                    .addComponent(txtThinking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(panBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panBottomLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(32, Short.MAX_VALUE)))
        );

        getContentPane().add(panBottom, java.awt.BorderLayout.SOUTH);

        lblModel.setText("Model");

        lblModelName.setText("Model Name");

        chkVision.setText("Vision");

        chkThink.setText("Think");

        javax.swing.GroupLayout panTopLayout = new javax.swing.GroupLayout(panTop);
        panTop.setLayout(panTopLayout);
        panTopLayout.setHorizontalGroup(
            panTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblModel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblModelName, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                .addComponent(chkVision)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkThink)
                .addContainerGap())
        );
        panTopLayout.setVerticalGroup(
            panTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTopLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(panTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModelName)
                    .addComponent(lblModel)
                    .addComponent(chkVision)
                    .addComponent(chkThink))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panTop, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        session.sendUserPrompt(txtPrompt.getText());
        txtPrompt.setText("");
    }//GEN-LAST:event_btnSendActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSend;
    private javax.swing.JCheckBox chkThink;
    private javax.swing.JCheckBox chkVision;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblModelName;
    private javax.swing.JLabel lblThinking;
    private javax.swing.JPanel panBottom;
    private javax.swing.JPanel panTop;
    private javax.swing.JScrollPane scroller;
    private javax.swing.JTextArea txtPrompt;
    private javax.swing.JTextArea txtResponse;
    private javax.swing.JTextField txtThinking;
    // End of variables declaration//GEN-END:variables
}
