/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.pb.aquajama;

import com.pb.aquajama.ollama.Token;
import com.pb.aquajama.sessions.Session;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.KeyStroke;
import javax.swing.text.DefaultEditorKit;

/**
 *
 * @author patrickballeux
 */
public class desktopSession extends javax.swing.JInternalFrame {

    private final Session session;

    /**
     * Creates new form desktopSession
     *
     * @param session
     */
    public desktopSession(Session session) {
        initComponents();
        this.session = session;
        this.setTitle("MODEL: %s".formatted(session.model.name()));
        session.setUiConsumer(token -> {
            javax.swing.SwingUtilities.invokeLater(() -> {
                // Basic append
                appendToken(token);
            });
        });
        txtResponse.setEditable(false);
        txtResponse.setWrapStyleWord(true);
        txtResponse.setLineWrap(true);

        lblModelName.setText(session.model.name());
        chkVision.setSelected(session.model.canUseVision());
        chkThink.setSelected(session.model.canThink());
        chkVision.setEnabled(false);
        chkThink.setEnabled(false);
        // Cross-platform copy binding
        int mask = Toolkit.getDefaultToolkit().getMenuShortcutKeyMaskEx();
        KeyStroke copyStroke = KeyStroke.getKeyStroke(KeyEvent.VK_C, mask);

        txtResponse.getInputMap().put(copyStroke, DefaultEditorKit.copyAction);
        txtResponse.getActionMap().get(DefaultEditorKit.copyAction);
        javax.swing.SwingUtilities.invokeLater(() -> txtPrompt.requestFocusInWindow());
        javax.swing.SwingUtilities.invokeLater(() -> this.pack());
    }

    private void appendToken(Token token) {

        if (token.isThinking()) {
            txtThinking.setText(txtThinking.getText().concat(token.text()));
            if (token.text().contains("\n")) {
                txtThinking.setText("");
            }
            return;
        }
        txtThinking.setText("");
        txtResponse.append(token.text());
        txtResponse.setCaretPosition(txtResponse.getDocument().getLength());
        sanitizeText();
    }

    private void sanitizeText() {
        String text = txtResponse.getText();
        int index1 = text.indexOf("```json");
        if (index1 >= 0){
            int index2 = text.indexOf("```", index1 + 6);
            if (index2 >= 0){
                text = text.substring(0, index1) + text.substring(index2+3);
                txtResponse.setText(text);
                txtResponse.setCaretPosition(txtResponse.getDocument().getLength());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scroller = new javax.swing.JScrollPane();
        txtResponse = new javax.swing.JTextArea();
        panBottom = new javax.swing.JPanel();
        txtPrompt = new javax.swing.JTextField();
        btnSend = new javax.swing.JButton();
        panTop = new javax.swing.JPanel();
        lblLabel = new javax.swing.JLabel();
        lblModelName = new javax.swing.JLabel();
        chkVision = new javax.swing.JCheckBox();
        chkThink = new javax.swing.JCheckBox();
        lblThinking = new javax.swing.JLabel();
        txtThinking = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Session");
        setSize(new java.awt.Dimension(456, 227));
        setVisible(true);

        txtResponse.setColumns(20);
        txtResponse.setRows(5);
        scroller.setViewportView(txtResponse);

        getContentPane().add(scroller, java.awt.BorderLayout.CENTER);

        txtPrompt.addActionListener(this::txtPromptActionPerformed);

        btnSend.setLabel("Send");
        btnSend.addActionListener(this::btnSendActionPerformed);

        javax.swing.GroupLayout panBottomLayout = new javax.swing.GroupLayout(panBottom);
        panBottom.setLayout(panBottomLayout);
        panBottomLayout.setHorizontalGroup(
            panBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBottomLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtPrompt, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSend)
                .addContainerGap())
        );
        panBottomLayout.setVerticalGroup(
            panBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBottomLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrompt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSend))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panBottom, java.awt.BorderLayout.SOUTH);

        lblLabel.setText("Model");

        lblModelName.setText("Model Name");

        chkVision.setText("Vision");

        chkThink.setText("Think");

        lblThinking.setText("Thinking");

        txtThinking.setEditable(false);
        txtThinking.setForeground(new java.awt.Color(153, 153, 153));
        txtThinking.setText(" ");

        javax.swing.GroupLayout panTopLayout = new javax.swing.GroupLayout(panTop);
        panTop.setLayout(panTopLayout);
        panTopLayout.setHorizontalGroup(
            panTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblThinking, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panTopLayout.createSequentialGroup()
                        .addComponent(lblModelName, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkVision)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkThink)
                        .addGap(0, 68, Short.MAX_VALUE))
                    .addComponent(txtThinking))
                .addContainerGap())
        );
        panTopLayout.setVerticalGroup(
            panTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTopLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(panTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModelName)
                    .addComponent(lblLabel)
                    .addComponent(chkVision)
                    .addComponent(chkThink))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblThinking)
                    .addComponent(txtThinking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        getContentPane().add(panTop, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPromptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPromptActionPerformed
        btnSend.doClick();
    }//GEN-LAST:event_txtPromptActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        session.sendUserPrompt(txtPrompt.getText());
        txtPrompt.setText("");
    }//GEN-LAST:event_btnSendActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSend;
    private javax.swing.JCheckBox chkThink;
    private javax.swing.JCheckBox chkVision;
    private javax.swing.JLabel lblLabel;
    private javax.swing.JLabel lblModelName;
    private javax.swing.JLabel lblThinking;
    private javax.swing.JPanel panBottom;
    private javax.swing.JPanel panTop;
    private javax.swing.JScrollPane scroller;
    private javax.swing.JTextField txtPrompt;
    private javax.swing.JTextArea txtResponse;
    private javax.swing.JTextField txtThinking;
    // End of variables declaration//GEN-END:variables
}
